Update cli.py, fix errors
fix errors :

1. TypeError: ImageCLI.draw_image() missing 1 required positional argument: 'parameters'

2. DrawImage.__init__() missing 1 required positional argument: 'image